projects:
  HealthAppApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: c3guxy46cnc63jjlavdirgnkya
        maxDepth: 5
extensions:
  amplify:
    version: 3
